/**
 * Template Generators
 *
 * Functions that generate the boilerplate files for users.
 */

export interface TemplateConfig {
  authPattern: "ctx-auth" | "custom" | "none";
  clientName: string;
  webhookPath: string;
  includeRecurringStreams: boolean;
  includeLiabilities: boolean;
}

/**
 * Generate convex/convex.config.ts content
 */
export function generateConvexConfig(): string {
  return `/**
 * Convex App Configuration
 *
 * This file registers the Plaid component with your Convex app.
 * Generated by @ericjamescrow/convex-plaid init
 */

import { defineApp } from "convex/server";
import plaid from "@ericjamescrow/convex-plaid/convex.config";

const app = defineApp();

// Register the Plaid component
app.use(plaid);

export default app;
`;
}

/**
 * Generate convex/http.ts content
 */
export function generateHttpRouter(config: { webhookPath: string }): string {
  return `/**
 * HTTP Router with Plaid Webhooks
 *
 * Handles Plaid webhook events for automatic syncing.
 * Generated by @ericjamescrow/convex-plaid init
 */

import { httpRouter } from "convex/server";
import { registerRoutes } from "@ericjamescrow/convex-plaid";
import { components } from "./_generated/api";

const http = httpRouter();

// =============================================================================
// PLAID WEBHOOKS
// =============================================================================

/**
 * Register Plaid webhook handler.
 *
 * Configure this URL in your Plaid Dashboard:
 * https://your-deployment.convex.site${config.webhookPath}
 */
registerRoutes(http, components.plaid, {
  webhookPath: "${config.webhookPath}",

  // Required for webhook signature verification and auto-sync
  plaidConfig: {
    PLAID_CLIENT_ID: process.env.PLAID_CLIENT_ID!,
    PLAID_SECRET: process.env.PLAID_SECRET!,
    PLAID_ENV: process.env.PLAID_ENV ?? "sandbox",
    ENCRYPTION_KEY: process.env.ENCRYPTION_KEY!,
  },

  // Optional: Custom webhook handler (runs after default processing)
  onWebhook: async (ctx, webhookType, webhookCode, itemId, payload) => {
    console.log(\`[Plaid Webhook] \${webhookType}.\${webhookCode} for \${itemId}\`);

    // Add custom logic here, e.g.:
    // - Send notifications to users
    // - Update your own tables
    // - Trigger additional workflows
  },
});

// =============================================================================
// OTHER ROUTES (optional)
// =============================================================================

// Add other HTTP routes as needed:
// import { httpAction } from "./_generated/server";
// http.route({
//   path: "/api/health",
//   method: "GET",
//   handler: httpAction(async () => new Response("OK")),
// });

export default http;
`;
}

/**
 * Generate .env.local.example content
 */
export function generateEnvExample(encryptionKey: string): string {
  return `# Plaid Configuration
# Get these from https://dashboard.plaid.com/team/keys

# Plaid Client ID
PLAID_CLIENT_ID=your_client_id_here

# Plaid Secret (use sandbox/development/production key based on environment)
PLAID_SECRET=your_secret_here

# Plaid Environment: sandbox | development | production
PLAID_ENV=sandbox

# Encryption key for access tokens (256-bit base64-encoded)
# Generated key (replace or regenerate with: node -e "console.log(require('crypto').randomBytes(32).toString('base64'))")
ENCRYPTION_KEY=${encryptionKey}
`;
}

/**
 * Generate convex/plaid.ts content
 */
export function generatePlaidWrapper(config: TemplateConfig): string {
  const { authPattern, clientName, includeRecurringStreams, includeLiabilities } = config;

  const authCheckAction = getAuthCheckAction(authPattern);
  const authCheckQuery = getAuthCheckQuery(authPattern);
  const getUserIdAction = getGetUserIdAction(authPattern);
  const getUserIdQuery = getGetUserIdQuery(authPattern);
  const userIdArg = authPattern === "custom" ? "\n    userId: v.string()," : "";

  let content = `/**
 * Plaid Integration Wrapper
 *
 * Authenticated wrapper actions for the Plaid component.
 * Generated by @ericjamescrow/convex-plaid init
 */

import { v } from "convex/values";
import { action, query, mutation } from "./_generated/server";
import { Plaid } from "@ericjamescrow/convex-plaid";
import { components } from "./_generated/api";

// =============================================================================
// PLAID CLIENT (LAZY INITIALIZATION)
// =============================================================================

/**
 * Lazy-initialized Plaid client.
 * Environment variables are only available at runtime.
 */
let _plaid: Plaid | null = null;

function getPlaid(): Plaid {
  if (!_plaid) {
    _plaid = new Plaid(components.plaid, {
      PLAID_CLIENT_ID: process.env.PLAID_CLIENT_ID!,
      PLAID_SECRET: process.env.PLAID_SECRET!,
      PLAID_ENV: process.env.PLAID_ENV ?? "sandbox",
      ENCRYPTION_KEY: process.env.ENCRYPTION_KEY!,
    });
  }
  return _plaid;
}

// =============================================================================
// LINK FLOW
// =============================================================================

/**
 * Create a link token for Plaid Link initialization.
 */
export const createLinkToken = action({
  args: {
    products: v.optional(v.array(v.string())),${userIdArg}
  },
  handler: async (ctx, args) => {
${authCheckAction}
${getUserIdAction}

    return await getPlaid().createLinkToken(ctx, {
      userId,
      products: args.products,
      clientName: "${clientName}",
      // Uncomment to enable webhooks:
      // webhookUrl: "https://your-deployment.convex.site/plaid/webhook",
    });
  },
});

/**
 * Exchange public token after Plaid Link success.
 */
export const exchangePublicToken = action({
  args: {
    publicToken: v.string(),${userIdArg}
  },
  handler: async (ctx, args) => {
${authCheckAction}
${getUserIdAction}

    // Exchange token and create plaidItem
    const result = await getPlaid().exchangePublicToken(ctx, {
      publicToken: args.publicToken,
      userId,
    });

    // Automatically onboard (fetch accounts, transactions, etc.)
    await getPlaid().onboardItem(ctx, {
      plaidItemId: result.plaidItemId,
    });

    return result;
  },
});

// =============================================================================
// SYNC OPERATIONS
// =============================================================================

/**
 * Manually sync transactions for a Plaid item.
 */
export const syncTransactions = action({
  args: {
    plaidItemId: v.string(),
  },
  handler: async (ctx, args) => {
${authCheckAction}

    return await getPlaid().syncTransactions(ctx, {
      plaidItemId: args.plaidItemId,
    });
  },
});

/**
 * Trigger a transaction refresh from the financial institution.
 */
export const triggerTransactionsRefresh = action({
  args: {
    plaidItemId: v.string(),
  },
  handler: async (ctx, args) => {
${authCheckAction}

    return await getPlaid().triggerTransactionsRefresh(ctx, {
      plaidItemId: args.plaidItemId,
    });
  },
});
`;

  if (includeLiabilities) {
    content += `
/**
 * Refresh liabilities data for a Plaid item.
 */
export const refreshLiabilities = action({
  args: {
    plaidItemId: v.string(),
  },
  handler: async (ctx, args) => {
${authCheckAction}

    return await getPlaid().fetchLiabilities(ctx, {
      plaidItemId: args.plaidItemId,
    });
  },
});
`;
  }

  if (includeRecurringStreams) {
    content += `
/**
 * Fetch recurring streams (subscriptions, income) for a Plaid item.
 */
export const fetchRecurringStreams = action({
  args: {
    plaidItemId: v.string(),
  },
  handler: async (ctx, args) => {
${authCheckAction}

    return await getPlaid().fetchRecurringStreams(ctx, {
      plaidItemId: args.plaidItemId,
    });
  },
});
`;
  }

  content += `
// =============================================================================
// RE-AUTH FLOW
// =============================================================================

/**
 * Create an update link token for re-authentication.
 * Use when a plaidItem has status "needs_reauth".
 */
export const createUpdateLinkToken = action({
  args: {
    plaidItemId: v.string(),
  },
  handler: async (ctx, args) => {
${authCheckAction}

    return await getPlaid().createUpdateLinkToken(ctx, {
      plaidItemId: args.plaidItemId,
    });
  },
});

/**
 * Complete re-authentication after update Link flow.
 */
export const completeReauth = action({
  args: {
    plaidItemId: v.string(),
  },
  handler: async (ctx, args) => {
${authCheckAction}

    return await getPlaid().completeReauth(ctx, {
      plaidItemId: args.plaidItemId,
    });
  },
});

// =============================================================================
// QUERIES
// =============================================================================

/**
 * Get all Plaid items for the current user.
 */
export const getMyItems = query({
  args: {${userIdArg}},
  handler: async (ctx, args) => {
${authCheckQuery}
${getUserIdQuery}

    return await ctx.runQuery(getPlaid().api.getItemsByUser, { userId });
  },
});

/**
 * Get all accounts for the current user.
 */
export const getMyAccounts = query({
  args: {${userIdArg}},
  handler: async (ctx, args) => {
${authCheckQuery}
${getUserIdQuery}

    return await ctx.runQuery(getPlaid().api.getAccountsByUser, { userId });
  },
});

/**
 * Get transactions for the current user.
 */
export const getMyTransactions = query({
  args: {
    startDate: v.optional(v.string()),
    endDate: v.optional(v.string()),
    limit: v.optional(v.number()),${userIdArg}
  },
  handler: async (ctx, args) => {
${authCheckQuery}
${getUserIdQuery}

    return await ctx.runQuery(getPlaid().api.getTransactionsByUser, {
      userId,
      startDate: args.startDate,
      endDate: args.endDate,
      limit: args.limit,
    });
  },
});
`;

  if (includeLiabilities) {
    content += `
/**
 * Get credit card liabilities for the current user.
 */
export const getMyLiabilities = query({
  args: {${userIdArg}},
  handler: async (ctx, args) => {
${authCheckQuery}
${getUserIdQuery}

    return await ctx.runQuery(getPlaid().api.getLiabilitiesByUser, { userId });
  },
});
`;
  }

  if (includeRecurringStreams) {
    content += `
/**
 * Get active subscriptions for the current user.
 */
export const getMySubscriptions = query({
  args: {${userIdArg}},
  handler: async (ctx, args) => {
${authCheckQuery}
${getUserIdQuery}

    return await ctx.runQuery(getPlaid().api.getActiveSubscriptions, { userId });
  },
});

/**
 * Get recurring income for the current user.
 */
export const getMyRecurringIncome = query({
  args: {${userIdArg}},
  handler: async (ctx, args) => {
${authCheckQuery}
${getUserIdQuery}

    return await ctx.runQuery(getPlaid().api.getRecurringIncome, { userId });
  },
});
`;
  }

  content += `
// =============================================================================
// MUTATIONS
// =============================================================================

/**
 * Delete a Plaid item and all associated data.
 */
export const deleteItem = mutation({
  args: {
    plaidItemId: v.string(),
  },
  handler: async (ctx, args) => {
${authCheckQuery}

    return await ctx.runMutation(getPlaid().api.deletePlaidItem, {
      plaidItemId: args.plaidItemId,
    });
  },
});
`;

  return content;
}

// Helper functions for auth patterns

function getAuthCheckAction(authPattern: string): string {
  switch (authPattern) {
    case "ctx-auth":
      return `    const identity = await ctx.auth.getUserIdentity();
    if (!identity) {
      throw new Error("Not authenticated");
    }`;
    case "custom":
      return `    // Custom auth - userId provided as argument`;
    case "none":
      return `    // No auth check - for testing only`;
    default:
      return "";
  }
}

function getAuthCheckQuery(authPattern: string): string {
  switch (authPattern) {
    case "ctx-auth":
      return `    const identity = await ctx.auth.getUserIdentity();
    if (!identity) {
      return [];
    }`;
    case "custom":
      return `    // Custom auth - userId provided as argument`;
    case "none":
      return `    // No auth check - for testing only`;
    default:
      return "";
  }
}

function getGetUserIdAction(authPattern: string): string {
  switch (authPattern) {
    case "ctx-auth":
      return `
    const userId = identity.subject;`;
    case "custom":
      return `
    const userId = args.userId;`;
    case "none":
      return `
    const userId = "anonymous";`;
    default:
      return "";
  }
}

function getGetUserIdQuery(authPattern: string): string {
  switch (authPattern) {
    case "ctx-auth":
      return `
    const userId = identity.subject;`;
    case "custom":
      return `
    const userId = args.userId;`;
    case "none":
      return `
    const userId = "anonymous";`;
    default:
      return "";
  }
}
